version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            sudo curl -LO https://nodejs.org/dist/v17.0.0/node-v17.0.0-linux-x64.tar.xz
            sudo tar -xvf node-v17.0.0-linux-x64.tar.xz
            sudo cp -r node-v17.0.0-linux-x64/{bin,include,lib,share} /usr/
            node --version => v17.0.0
            sudo apt install nodejs

            echo "--------- The images is Building ----"

            docker build -t udagram-api ./udagram-api
            docker tag udagram-api jameskaranja/udagram-api:v13

            echo "-------- All images succesfully built----------"

            echo " ------- login in to hub--------"

            docker login -u jameskaranja -p $DOCKERPASS

            echo "-------------- Pushing images to dockerhub-------"

            
            docker push jameskaranja/udagram-api:v13

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]


